linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - dogsled
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gomnd
    - gosec
    - importas
    - nestif
    - nilerr
    - nlreturn
    - unconvert
    - unparam
    - wastedassign
    - whitespace
