/*
Basis Theory API

## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package basistheory

import (
	"encoding/json"
)

// checks if the CreateTenantConnectionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTenantConnectionRequest{}

// CreateTenantConnectionRequest struct for CreateTenantConnectionRequest
type CreateTenantConnectionRequest struct {
	Strategy string                  `json:"strategy"`
	Options  TenantConnectionOptions `json:"options"`
}

// NewCreateTenantConnectionRequest instantiates a new CreateTenantConnectionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTenantConnectionRequest(strategy string, options TenantConnectionOptions) *CreateTenantConnectionRequest {
	this := CreateTenantConnectionRequest{}
	this.Strategy = strategy
	this.Options = options
	return &this
}

// NewCreateTenantConnectionRequestWithDefaults instantiates a new CreateTenantConnectionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTenantConnectionRequestWithDefaults() *CreateTenantConnectionRequest {
	this := CreateTenantConnectionRequest{}
	return &this
}

// GetStrategy returns the Strategy field value
func (o *CreateTenantConnectionRequest) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *CreateTenantConnectionRequest) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *CreateTenantConnectionRequest) SetStrategy(v string) {
	o.Strategy = v
}

// GetOptions returns the Options field value
func (o *CreateTenantConnectionRequest) GetOptions() TenantConnectionOptions {
	if o == nil {
		var ret TenantConnectionOptions
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *CreateTenantConnectionRequest) GetOptionsOk() (*TenantConnectionOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *CreateTenantConnectionRequest) SetOptions(v TenantConnectionOptions) {
	o.Options = v
}

func (o CreateTenantConnectionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTenantConnectionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strategy"] = o.Strategy
	toSerialize["options"] = o.Options
	return toSerialize, nil
}

type NullableCreateTenantConnectionRequest struct {
	value *CreateTenantConnectionRequest
	isSet bool
}

func (v NullableCreateTenantConnectionRequest) Get() *CreateTenantConnectionRequest {
	return v.value
}

func (v *NullableCreateTenantConnectionRequest) Set(val *CreateTenantConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTenantConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTenantConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTenantConnectionRequest(val *CreateTenantConnectionRequest) *NullableCreateTenantConnectionRequest {
	return &NullableCreateTenantConnectionRequest{value: val, isSet: true}
}

func (v NullableCreateTenantConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTenantConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
