/*
BasisTheory Vault API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package basistheory

import (
	"encoding/json"
)

// ReactorModelPaginatedList struct for ReactorModelPaginatedList
type ReactorModelPaginatedList struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Data []ReactorModel `json:"data,omitempty"`
}

// NewReactorModelPaginatedList instantiates a new ReactorModelPaginatedList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReactorModelPaginatedList() *ReactorModelPaginatedList {
	this := ReactorModelPaginatedList{}
	return &this
}

// NewReactorModelPaginatedListWithDefaults instantiates a new ReactorModelPaginatedList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReactorModelPaginatedListWithDefaults() *ReactorModelPaginatedList {
	this := ReactorModelPaginatedList{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ReactorModelPaginatedList) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactorModelPaginatedList) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ReactorModelPaginatedList) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ReactorModelPaginatedList) SetPagination(v Pagination) {
	o.Pagination = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReactorModelPaginatedList) GetData() []ReactorModel {
	if o == nil {
		var ret []ReactorModel
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReactorModelPaginatedList) GetDataOk() ([]ReactorModel, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReactorModelPaginatedList) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []ReactorModel and assigns it to the Data field.
func (o *ReactorModelPaginatedList) SetData(v []ReactorModel) {
	o.Data = v
}

func (o ReactorModelPaginatedList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableReactorModelPaginatedList struct {
	value *ReactorModelPaginatedList
	isSet bool
}

func (v NullableReactorModelPaginatedList) Get() *ReactorModelPaginatedList {
	return v.value
}

func (v *NullableReactorModelPaginatedList) Set(val *ReactorModelPaginatedList) {
	v.value = val
	v.isSet = true
}

func (v NullableReactorModelPaginatedList) IsSet() bool {
	return v.isSet
}

func (v *NullableReactorModelPaginatedList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReactorModelPaginatedList(val *ReactorModelPaginatedList) *NullableReactorModelPaginatedList {
	return &NullableReactorModelPaginatedList{value: val, isSet: true}
}

func (v NullableReactorModelPaginatedList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReactorModelPaginatedList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


