/*
Basis Theory API

## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package basistheory

import (
	"encoding/json"
)

// ProxyTransform struct for ProxyTransform
type ProxyTransform struct {
	Code NullableString `json:"code,omitempty"`
}

// NewProxyTransform instantiates a new ProxyTransform object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxyTransform() *ProxyTransform {
	this := ProxyTransform{}
	return &this
}

// NewProxyTransformWithDefaults instantiates a new ProxyTransform object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyTransformWithDefaults() *ProxyTransform {
	this := ProxyTransform{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProxyTransform) GetCode() string {
	if o == nil || isNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProxyTransform) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *ProxyTransform) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *ProxyTransform) SetCode(v string) {
	o.Code.Set(&v)
}

// SetCodeNil sets the value for Code to be an explicit nil
func (o *ProxyTransform) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *ProxyTransform) UnsetCode() {
	o.Code.Unset()
}

func (o ProxyTransform) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableProxyTransform struct {
	value *ProxyTransform
	isSet bool
}

func (v NullableProxyTransform) Get() *ProxyTransform {
	return v.value
}

func (v *NullableProxyTransform) Set(val *ProxyTransform) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyTransform) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyTransform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyTransform(val *ProxyTransform) *NullableProxyTransform {
	return &NullableProxyTransform{value: val, isSet: true}
}

func (v NullableProxyTransform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyTransform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
