/*
BasisTheory Vault API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package basistheory

import (
	"encoding/json"
)

// ApplicationModelPaginatedList struct for ApplicationModelPaginatedList
type ApplicationModelPaginatedList struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Data []ApplicationModel `json:"data,omitempty"`
}

// NewApplicationModelPaginatedList instantiates a new ApplicationModelPaginatedList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationModelPaginatedList() *ApplicationModelPaginatedList {
	this := ApplicationModelPaginatedList{}
	return &this
}

// NewApplicationModelPaginatedListWithDefaults instantiates a new ApplicationModelPaginatedList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationModelPaginatedListWithDefaults() *ApplicationModelPaginatedList {
	this := ApplicationModelPaginatedList{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ApplicationModelPaginatedList) GetPagination() Pagination {
	if o == nil || o.Pagination == nil {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationModelPaginatedList) GetPaginationOk() (*Pagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ApplicationModelPaginatedList) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ApplicationModelPaginatedList) SetPagination(v Pagination) {
	o.Pagination = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApplicationModelPaginatedList) GetData() []ApplicationModel {
	if o == nil {
		var ret []ApplicationModel
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApplicationModelPaginatedList) GetDataOk() ([]ApplicationModel, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApplicationModelPaginatedList) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []ApplicationModel and assigns it to the Data field.
func (o *ApplicationModelPaginatedList) SetData(v []ApplicationModel) {
	o.Data = v
}

func (o ApplicationModelPaginatedList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationModelPaginatedList struct {
	value *ApplicationModelPaginatedList
	isSet bool
}

func (v NullableApplicationModelPaginatedList) Get() *ApplicationModelPaginatedList {
	return v.value
}

func (v *NullableApplicationModelPaginatedList) Set(val *ApplicationModelPaginatedList) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationModelPaginatedList) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationModelPaginatedList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationModelPaginatedList(val *ApplicationModelPaginatedList) *NullableApplicationModelPaginatedList {
	return &NullableApplicationModelPaginatedList{value: val, isSet: true}
}

func (v NullableApplicationModelPaginatedList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationModelPaginatedList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


