/*
Basis Theory API

## Getting Started * Sign-in to [Basis Theory](https://basistheory.com) and go to [Applications](https://portal.basistheory.com/applications) * Create a Basis Theory Private Application * All permissions should be selected * Paste the API Key into the `BT-API-KEY` variable

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package basistheory

import (
	"encoding/json"
)

// checks if the ThreeDSMobileSdkRenderOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThreeDSMobileSdkRenderOptions{}

// ThreeDSMobileSdkRenderOptions struct for ThreeDSMobileSdkRenderOptions
type ThreeDSMobileSdkRenderOptions struct {
	SdkInterface NullableString `json:"sdk_interface,omitempty"`
	SdkUiType    []string       `json:"sdk_ui_type,omitempty"`
}

// NewThreeDSMobileSdkRenderOptions instantiates a new ThreeDSMobileSdkRenderOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThreeDSMobileSdkRenderOptions() *ThreeDSMobileSdkRenderOptions {
	this := ThreeDSMobileSdkRenderOptions{}
	return &this
}

// NewThreeDSMobileSdkRenderOptionsWithDefaults instantiates a new ThreeDSMobileSdkRenderOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThreeDSMobileSdkRenderOptionsWithDefaults() *ThreeDSMobileSdkRenderOptions {
	this := ThreeDSMobileSdkRenderOptions{}
	return &this
}

// GetSdkInterface returns the SdkInterface field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreeDSMobileSdkRenderOptions) GetSdkInterface() string {
	if o == nil || IsNil(o.SdkInterface.Get()) {
		var ret string
		return ret
	}
	return *o.SdkInterface.Get()
}

// GetSdkInterfaceOk returns a tuple with the SdkInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreeDSMobileSdkRenderOptions) GetSdkInterfaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SdkInterface.Get(), o.SdkInterface.IsSet()
}

// HasSdkInterface returns a boolean if a field is not nil.
func (o *ThreeDSMobileSdkRenderOptions) HasSdkInterface() bool {
	if o != nil && !IsNil(o.SdkInterface) {
		return true
	}

	return false
}

// SetSdkInterface gets a reference to the given NullableString and assigns it to the SdkInterface field.
func (o *ThreeDSMobileSdkRenderOptions) SetSdkInterface(v string) {
	o.SdkInterface.Set(&v)
}

// SetSdkInterfaceNil sets the value for SdkInterface to be an explicit nil
func (o *ThreeDSMobileSdkRenderOptions) SetSdkInterfaceNil() {
	o.SdkInterface.Set(nil)
}

// UnsetSdkInterface ensures that no value is present for SdkInterface, not even an explicit nil
func (o *ThreeDSMobileSdkRenderOptions) UnsetSdkInterface() {
	o.SdkInterface.Unset()
}

// GetSdkUiType returns the SdkUiType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ThreeDSMobileSdkRenderOptions) GetSdkUiType() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SdkUiType
}

// GetSdkUiTypeOk returns a tuple with the SdkUiType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ThreeDSMobileSdkRenderOptions) GetSdkUiTypeOk() ([]string, bool) {
	if o == nil || IsNil(o.SdkUiType) {
		return nil, false
	}
	return o.SdkUiType, true
}

// HasSdkUiType returns a boolean if a field is not nil.
func (o *ThreeDSMobileSdkRenderOptions) HasSdkUiType() bool {
	if o != nil && !IsNil(o.SdkUiType) {
		return true
	}

	return false
}

// SetSdkUiType gets a reference to the given []string and assigns it to the SdkUiType field.
func (o *ThreeDSMobileSdkRenderOptions) SetSdkUiType(v []string) {
	o.SdkUiType = v
}

func (o ThreeDSMobileSdkRenderOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThreeDSMobileSdkRenderOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.SdkInterface.IsSet() {
		toSerialize["sdk_interface"] = o.SdkInterface.Get()
	}
	if o.SdkUiType != nil {
		toSerialize["sdk_ui_type"] = o.SdkUiType
	}
	return toSerialize, nil
}

type NullableThreeDSMobileSdkRenderOptions struct {
	value *ThreeDSMobileSdkRenderOptions
	isSet bool
}

func (v NullableThreeDSMobileSdkRenderOptions) Get() *ThreeDSMobileSdkRenderOptions {
	return v.value
}

func (v *NullableThreeDSMobileSdkRenderOptions) Set(val *ThreeDSMobileSdkRenderOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableThreeDSMobileSdkRenderOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableThreeDSMobileSdkRenderOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThreeDSMobileSdkRenderOptions(val *ThreeDSMobileSdkRenderOptions) *NullableThreeDSMobileSdkRenderOptions {
	return &NullableThreeDSMobileSdkRenderOptions{value: val, isSet: true}
}

func (v NullableThreeDSMobileSdkRenderOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThreeDSMobileSdkRenderOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
