name: Pre-Release

on:
  push:
    branches: [ pre-release ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install svu
        run: |
          echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
          sudo apt update
          sudo apt install svu

      - name: Install semver
        run: |
          sudo apt install nodejs
          sudo apt install npm
          npm install --no-progress -g semver

      - name: Get new tag
        id: get-new-tag
        run: |
          CURRENT_GIT_TAG=$(svu current)
          NEXT_GIT_TAG=$(semver $CURRENT_GIT_TAG -i prerelease --preid rc)
          echo "::set-output name=nextTag::$NEXT_GIT_TAG"

      - name: Tag
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{ steps.get-new-tag.outputs.nextTag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
