name: Pull Request
on:
  pull_request:
    branches: [ master, pre-release ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42

  test:
    name: Unit test
    strategy:
      matrix:
        go-version: [ '1.16', '1.17' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run unit tests
        run: make verify
        env:
          SKIP_LINT: 1 # linting run in different job
