name: Pull Request
on:
  pull_request:
    branches: [ master, pre-release ]
jobs:
  acceptance-test:
    name: Acceptance test
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PRIVATE_PACKAGE_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run acceptance tests
        run: make verify
