name: Pull Request
on:
  pull_request:
    branches: [ master, pre-release ]
jobs:
  test:
    name: Unit test
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run unit tests
        run: make verify
