name: Pull Request
on:
  pull_request:
    branches: [master]
jobs:
  test:
    name: Lint and test (unit)
    strategy:
      matrix:
        go-version: [ '1.16', '1.17' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify Lint and Unit tests
        run: make verify
