name: Release

on:
  push:
    branches: [ master, pre-release ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Version and Tag
        id: bump_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          pre_release_branches: pre-release
          append_to_pre_release_tag: 'rc-${{ github.run_id }}'
