name: Verify
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: Which repo triggered this workflow run
        required: true
  pull_request:
    branches: [ master, pre-release ]

jobs:
  testing-tagging:
    name: Testing tagging
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install svu
        run: |
          echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
          sudo apt update -qq
          sudo apt install -qq svu

      - name: Get new tag
        id: get-new-tag
        run: |
          CURRENT_GIT_TAG=$(svu current)
          NEXT_GIT_TAG=$(svu)
          echo "::set-output name=nextTag::$NEXT_GIT_TAG"
          echo "::set-output name=currentTag::v$CURRENT_GIT_TAG"

      - name: Tag
        if: ${{ steps.get-new-tag.outputs.nextTag != steps.get-new-tag.outputs.currentTag }}
        run: |
          echo "You should not see this!"

  acceptance-test:
    name: Acceptance test triggered by ${{ github.event.inputs.source || github.event_name }}
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PRIVATE_PACKAGE_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VAULT_SSH_PRIVATE_KEY }}

      - name: Run acceptance tests
        run: make verify
        env:
          IS_PR_WORKFLOW: true
