name: Verify
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go build
        run: |
          go build .
