name: Verify
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18', '1.19' '1.20' ]
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run acceptance tests
        run: make verify
        env:
          BASISTHEORY_API_URL: "https://api.flock-dev.com"
          BASISTHEORY_MGMT_API_KEY: ${{ secrets.BASISTHEORY_MGMT_API_KEY }}
          BASISTHEORY_SRVR_API_KEY: ${{ secrets.BASISTHEORY_SRVR_API_KEY }}
